version: '3.8'

networks:
  default:

services:
  db:
    image: postgres:latest
    platform: linux/arm64/v8  # For M1/M2 Macs
    container_name: banjo-db
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: banjo_user
      POSTGRES_PASSWORD: banjo_password
      POSTGRES_DB: banjo_db