networks:
  default:

services:
  db:
    image: postgres:latest
    platform: linux/arm64/v8 # For M1/M2 Macs
    container_name: banjo-db
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: woodjohn/banjo:latest # Tag the image
    container_name: banjo-app
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
    depends_on:
      - db
